### PR TITLE
http/https

### LINKED ISSUE #9: FeedWriter does not honor actual (or proxied) protocol
When serving the feed behind an SSL terminating endpoint (say, nginx as a reverse proxy), the download feeds are in the wrong format. The protocol should generally match the value of the `X-Forwarded-Proto` request header (which is either missing, `http` or `https` in this case).

### PR DESCRIPTION
**Pull request by helge000**
(sorry, accidentally hit enter before I actually added the stuff below)

### Three small changes:
- Add a function to find out whatever we are running HTTPS or HTTP,  should fix #9 
- Fixes `Undefined index` error by using `SERVER_NAME` instead `HTTP_HOST`
- Ignore `*.nupkg` files

Pls let me know whatever you want this squashed.

### CODE REVIEW

File: inc/core.php [hunk 1]
```diff
@@ -55,3 +55,12 @@ function get_package_path($id, $version) {
 	// This is safe - These values have been validated via validateIdAndVersion above
 	return '/packagefiles/' . $id . '/' . $version . '.nupkg';
 }
+
+/* Used to construct URIs */
+function http_https() {
```
Comment (Daniel15) [inline inc/core.php]: Maybe call this `url_scheme` instead?

File: inc/feedwriter.php [hunk 2]
```diff
@@ -6,8 +6,8 @@ class FeedWriter {
 	public function __construct($id) {
 		$this->feedID = $id;
 		$this->baseURL =
-			'http://' .
-			$_SERVER['HTTP_HOST'] .
+			http_https() .
+			$_SERVER['SERVER_NAME'] .
```
Comment (Daniel15) [inline inc/feedwriter.php]: Is SERVER_NAME always defined? What's the difference between HTTP_HOST and SERVER_NAME?

File: inc/core.php (hunk 1 above)
Comment (helge000) [inline inc/core.php]: I am far from an expert in PHP; I just asked [StackOverflow](https://stackoverflow.com/questions/7304182/detecting-ssl-with-php) about the most reliable way to detect HTTPS, all pointed to the [`$_SERVER` array](http://www.php.net/manual/en/reserved.variables.server.php)

File: inc/feedwriter.php (hunk 2 above)
Comment (helge000) [inline inc/feedwriter.php]: Ditto, but I read the [server array doc](http://www.php.net/manual/en/reserved.variables.server.php) in this way:
- `HTTP_HOST` is reading from a header field (thus set by the client itself) witch might be undefined in certain circumstances (I had it when using some old cURL libs)
- `SERVER_NAME` is set by the http server itself, and therefore always populated.

> You should now however realize that the one is a client-controlled value which may thus not be reliable for use in business logic and the other is a server-controlled value which is more reliable. You however need to ensure that the webserver in question has the SERVER_NAME correctly configured.
https://stackoverflow.com/a/2297421

File: inc/core.php (hunk 1 above)
Comment (helge000) [inline inc/core.php]: Ah, sorry - did not get it - may I refactor this when I squash?

File: public/index.php [hunk 3]
```diff
@@ -8,10 +8,10 @@
 }
 
 header('Content-Type: text/xml; charset=utf-8');
-$base_url = 'http://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['SCRIPT_NAME']);
+$base_url = http_https() . $_SERVER['SERVER_NAME'] . dirname($_SERVER['SCRIPT_NAME']);
 echo "<" . "?xml version='1.0' encoding='utf-8' standalone='yes'?>";
 ?>
-<service xml:base="<?= $base_url ?>/"
```
Comment (Daniel15) [inline public/index.php]: Rather than removing the slash here, perhaps we should do `rtrim($base_url, '/')` (to remove any existing trailing slash) and then always append `/`.

File: inc/core.php (hunk 1 above)
Comment (Daniel15) [inline inc/core.php]: Sure :)

btw you don't need to manually squash your commits, I can do it automatically in the Github UI when merging the pull request.

**Comment by helge000** [comment]
Na, I'll rebase, no sweat ;)
Hope this catches all your remarks.
